---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    yum:
      name:
      - aide
      state: latest
  - name: Start service aide, if not started
      name: Start Autonomous Database
      oci_database_autonomous_database_actions:
         autonomous_database_id: "{{ aide }}"
         action: start
   
     
