---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    yum:
      name:
      - aide
      state: latest
  - name: Start service aide, if not started
     enable:
        name: 
          - aide
   
     
