--- 
- name: Install only particular updates based on the KB numbers
  hosts: all
  tasks:
    - name: Security Update Adobe Flash Player 
      ansible.windows.win_updates:
        category_name:
          - SecurityUpdates
        whitelist:
          - KB4580325
    
