--- 
- hosts: all
  name: Install only particular updates based on the KB numbers
  tasks:
    ansible.windows.win_updates:
      category_name:
        - SecurityUpdates
      whitelist:
        - KB4580325
    
